### ISSUE TITLE
[Bug] Table-sortable

### ISSUE THREAD

**Issue by GN19293** [creativetimofficial/ct-vue-argon-dashboard-pro#39]
### Version
Version 2.0.0
### Reproduction link
https://dashboard.exseedhealth.com/
### Operating System
Big sur version 11.1
### Device
Mac book pro
### Browser & Version
Chrome 89.0.4389.90
### Steps to reproduce
- Creating a sortable table.
- Host the project on AWS Amplify
- Access the page
### What is expected?
The sorting icons, arrow up and down should be visible.
### What is actually happening?
Not getting displayed

---

**Comment by rarestoma** [comment]
Hi @GN19293,

Thank you for working with our products.

Unfortunately, I can not access the website as I can't create an account. Can you please send me a short video so I can see clearly what happens and test it?

Thank you,
Rares

**Comment by GN19293** [comment]
<img width="1058" alt="Screenshot 2021-03-29 at 16 17 36" src="https://user-images.githubusercontent.com/81574289/112947462-1ebf1480-9137-11eb-8fce-fa0ef4093eba.png">
Hi Rares

As you can see in the image, the sorting arrows up/down on STATUS only appears when you click on it. I wanted to make these arrows visible as default. 

BR

Gin

**Comment by rarestoma** [comment]
Hi @GN19293,

Please go to src/assets/sass/core/vendors/_element-tables.scss and, on line 21 and 29, add !important after defining the border color:

```
...
.ascending .sort-caret.ascending {
    border-bottom-color: theme-color("default") !important;
  }

  .sort-caret.descending {
    bottom: 9px;
  }

  .descending .sort-caret.descending {
    border-top-color: theme-color("default") !important;
  }
...
```

This should fix this issue.

Please let me know if it works.

Thank you,
Rares

**Comment by GN19293** [comment]
Hi Rares

Thank you for the answer, it works on localhost, but still not on the AWS amplify.

BR

Gin

**Comment by rarestoma** [comment]
Hi @GN19293,

Unfortunately, we do not have experience with AWS amplify but we will try to find a solution. Do you get any errors in AWS?

Thank you,
Rares

**Comment by sajadevo** [comment]
**Hi there,**

We've updated the product to v3 which comes with a new look and a new base structure for more reusable components.

**All the best**
**Sajad**

**Web Developer @ [Creative-Tim.com](http://creative-tim.com/)**
